apiVersion: "v1"
name: nginx-with-monitoring
version: 3.0.0
appVersion: v0.0.1
kubeVersion: "^1.10.0-0"
description: "Nginx-app deployment with "
maintainers:
- name: Dzmitry Zarubo
  email: dmitri20023zarubo@gmail.com