apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-application-svc
  namespace: {{ .Values.application.namespace | default "default" | quote }}
spec:
  ports:
    {{- toYaml .Values.application.svc.ports | nindent 4}}
  selector:
    {{- include "nginx-app.labels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.application.svc.type }}