global:
  resolve_timeout: 5m
metadata:
  name: slack-alertmanager
  labels:
    alertmanagerConfig: slack
  namespace: Sisoitherembo
route:
  group_by: ['example']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 5m
  receiver: 'slack'
receivers:
  - name: 'slack'
    slackConfigs:
    - sendResolved: true
      apiURL:
        name: slack-secret
        key: 'https://hooks.slack.com/services/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'
      channel: '#alerting-prometheus'
      title: '{{ template "alert_title" . }}'
      text: '{{ template "alert_description" . }}'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']