global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  group_by: ['example']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 5m
  receiver: 'slack'
receivers:
  - name: 'slack'
    slack_configs:
    - channel: '#alerting-prometheus'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

