global:
  resolve_timeout: 5m
route:
  group_by: ['example']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 5m
  receiver: 'slack'
receivers:
  - name: 'slack'
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: 	'#alerting-prometheus'
        send_resolved: true
        text: "\nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }} "
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

