version: "3"

networks:
  loki:

volumes:
  grafana-data:
  promtail-data:

services:
  loki:
    image: grafana/loki:2.6.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
      - ./loki-config.yml:/etc/loki/config.yaml

  #promtail:
  #  image: grafana/promtail:2.6.0
  #  container_name: promtail
  #  volumes:
  #      - /var/lib/docker/containers:/var/lib/docker/containers
  #      - ./promtail-config.yml:/etc/promtail/promtail.yml:ro
  #      - promtail-data:/var/lib/promtail/positions
  #  command: -config.file=/etc/promtail/config.yml
  #  networks:
  #    - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana