- name: "Launch Docker-images on EC2-servers"
  hosts: ec2_servers
  become: True
  gather_facts: False 
  
  vars:
    docker_image_nginx: sisoitherembo/nginx-app:latest
    docker_image_apache: sisoitherembo/apache-app:latest
    docker_network: my-net
    docker_username: sisoitherembo
    docker_email: dmitri20023zarubo@gmail.com

  vars_prompt:
    - name: docker_password
      prompt: "Enter dockerhub password"
      private: yes 
  
  tasks:
    - name: Get docker-install script
      command: curl -fsSL https://get.docker.com -o get-docker.sh 

    - name: Install Docker
      command: sh get-docker.sh
    
    - name: Install Python3-pip
      apt: 
        name: python3-pip 
        update_cache: yes

    - name: Install docker-py
      command: pip3 install docker-py
    
    - name: Start Docker
      command: service docker start
      
    - name: Authenticate with repository
      docker_login: 
        username: "{{ docker_username }}"
        email:    "{{ docker_email }}"
        password: "{{ docker_password }}"
    
    - name: Create Docker network
      docker_network: name="{{ docker_network }}"
    - name: Start apache-app
      docker_container: 
        name: apache-app
        image: "{{ docker_image_apache }}"
        pull: yes
        networks: 
          - name: "{{ docker_network }}"
        ports: 
          - "8080:80"
    
    - name: Start nginx-app
      docker_container: 
        name: nginx-app
        image: "{{ docker_image_nginx }}"
        pull: yes
        networks: 
          - name: "{{ docker_network }}"
        ports: 
          - "80:80"

