apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-app-configmap
  namespace : nginx-app
  labels: 
    app : nginx-app
    env : prod
data:
  apache.ports.conf: |
Listen 8086
<IfModule ssl_module>
        Listen 443
</IfModule>
<IfModule mod_gnutls.c>
        Listen 443
</IfModule>
  nginx.server.conf: |
    upstream apache{
            server localhost:8086;
    }
    server {
            server_name "" $server_addr;
            listen 80; # managed by Certbot
            root /home/nginx-user/public_html;
            index index.html;

            location /info.php {
                    proxy_pass http://apache/$uri;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-for $remote_addr;
                    proxy_set_header Host $host;
                    proxy_connect_timeout 60;
                    proxy_send_timeout 90;
                    proxy_read_timeout 90;
                    proxy_redirect off;
                    proxy_set_header Connection close;
                    proxy_pass_header Content-Type;
                    proxy_pass_header Content-Disposition;
                    proxy_pass_header Content-Length;
            }

            location /application {
                    proxy_pass  http://app;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-for $remote_addr;
                    proxy_set_header Host $host;
            }

            location ~ "\.mp3" {
                try_files $uri =404;
            }

            location /secondserver {
                rewrite ^ https://www.youtube.com/watch?v=dQw4w9WgXcQ;
            }

            location /roundrobin {
                    proxy_pass http://balance;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-for $remote_addr;
                    proxy_set_header Host $host;

            }

            location ~ "^.*/(?<angle>0|90|180|270|360)?/(?<file>\w+)\.(?<format>jpg|jpeg)$" {
                    alias /home/nginx-user/public_html/data/Images/$file.$format;
                    add_header Capture1 $angle;
                    add_header Capture2 $file;
                    add_header Capture3 $format;
                    add_header Capture4 $uri;

                    image_filter test;
                    image_filter rotate $angle;
                    image_filter_buffer 8M;
            }

            location ~ "^/(?<file>\w+)?\.(png)$" {
                    root /home/nginx-user/public_html/data/Images/;
                    add_header Capture1 $file;
                    add_header Capture2 $uri;
                    image_filter test;
                    image_filter_buffer 8M;
            }

            location /monitoring {
                    root /home/nginx-user/public_html/;
                    index monitoring.html =404;
                    add_header Refresh 1;
            }
        }

    upstream app {
            server localhost:8080;
    }
    server {
            listen 8080;
            server_name "" $server_addr;
            root /home/nginx-user/public_html/;
            index app.html;
    }
  nginx.roundrobin.conf: |
    upstream balance {
        server localhost:8081;
        server localhost:8082;   
    }
    server {
            server_name "" $server_addr;
            listen 8081;
            location /roundrobin {
                    root /home/nginx-user/public_html;
                    index index1.html =404;
                    add_header Last-Modified $date_gmt;
                    add_header Cache-Control 'no-store, no-cache';
                    if_modified_since off;
                    expires off;
                    etag off;
            }
    }
    server {
            server_name "" $server_addr;
            listen 8082;
            location /roundrobin {
                    root /home/nginx-user/public_html;
                    index index2.html =404;
                    add_header Last-Modified $date_gmt;
                    add_header Cache-Control 'no-store, no-cache';
                    if_modified_since off;
                    expires off;
                    etag off;
            }
    }
