apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deployment
  namespace: nginx-app
  labels:
    app: nginx-app
    env: prod 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
      env : prod
  template:
    metadata:
      labels:
        app: nginx-app
        env : prod
    spec:
      containers:
        - name: nginx-app
          image: sisoitherembo/nginx-app:k8s
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          volumeMounts:
            - name: nginx-config-nginx
              mountPath: "/etc/nginx/"
              subPath: "nginx.conf"
              readOnly: true
            - name: nginx-config-server
              mountPath: "/etc/nginx/conf.d/"
              subPath: "server.conf"
              readOnly: true
            - name: nginx-config-roundrobin
              mountPath: "/etc/nginx/conf.d/"
              subPath: "roundrobin.conf"
              readOnly: true
          #livenessProbe:
          #  httpGet:
          #    scheme: http
          #    port: probe
          #    path: /monitoring
          #  initialDelaySeconds: 10
          #  failureThreshold: 1
          #  periodSeconds: 10
          #startupProbe:
          #  httpGet:
          #    scheme: http
          #    port: probe
          #    path: /monitoring
          #  failureThreshold: 30
          #  periodSeconds: 10
          #readinessProbe:
          #    exec:
          #      command:
          #      - cat
          #      - /home/nginx-user/public_html/index.html
          #    initialDelaySeconds: 5
          #    periodSeconds: 5

        - name: apache-app 
          image: sisoitherembo/apache-app:k8s
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8086
          volumeMounts:
          - name: apache-config
            mountPath: "/etc/apache2/ports.conf"
            subPath: "ports.conf"
            readOnly: true
          #livenessProbe:
          #  httpGet:
          #    scheme: http
          #    port: probe
          #    path: /
          #  initialDelaySeconds: 10
          #  failureThreshold: 1
          #  periodSeconds: 10
          #startupProbe:
          #  httpGet:
          #    scheme: http
          #    port: probe
          #    path: /
          #  failureThreshold: 30
          #  periodSeconds: 10
          #readinessProbe:
          #    exec:
          #      command:
          #      - cat
          #      - /var/www/html/info.php
          #    initialDelaySeconds: 5
          #    periodSeconds: 5
      volumes:
        - name: nginx-config-nginx
          configMap:
            name: nginx-app-configmap
            items:
              - key: "nginx.nginx.conf"
                path: "nginx.conf"
        - name: nginx-config-server
          configMap:
            name: nginx-app-configmap
            items:
              - key: "nginx.server.conf"
                path: "conf.d/server.conf"
        - name: nginx-config-roundrobin
          configMap:
            name: nginx-app-configmap
            items:
              - key: "nginx.roundrobin.conf"
                path: "conf.d/roundrobin.conf"
        - name: apache-config
          configMap:
            name: nginx-app-configmap
            items:
              - key: "apache.ports.conf"
                path: "ports.conf"

