apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: nginx-app-service
  namespace: nginx-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
    #- name: https
    #  port: 443
    #  targetPort: 443
    #  nodePort: 31000
    #  protocol: TCP
  selector:
    app: nginx-app
    env: prod
  sessionAffinity: None
  type: NodePort