apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-app-service
  namespace: nginx-app
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
      protocol: TCP
  selector:
    app: nginx-app
    env: prod
  sessionAffinity: None
  type: NodePort