version: "0.0.1"

networks:
  prometheus-net:

services: 
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
    container_name: node-exporter
    volumes:
      - /:/rootfs:ro
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
    ports:
      - 9100:9100
    networks:
      - prometheus-net
    restart: always
    deploy:
      mode: global