version: 0.2

run-as: root

env:
  parameter-store: 
    docker_login: DOCKERHUB_LOGIN
    docker_password: DOCKERHUB_PASSWORD
  variables:
    REPO1: 245915323250.dkr.ecr.us-east-2.amazonaws.com/codepipeline-apache
    REPO2: 245915323250.dkr.ecr.us-east-2.amazonaws.com/codepipeline-nginx
    APP1: 'apache-app'
    APP2: 'nginx-app'
    DFILE1: "apache.dockerfile"
    DFILE2: "nginx.dockerfile"
    FOLDER1: "apache-config"
    FOLDER2: "nginx-config"
    STATIC_FILES: "nginx-config/nginx-user/**/*"

phases:
  pre_build:
    commands:
      - echo "Starting logging to aws cli"
      - echo "Docker-ce started!!!"
  build:
    commands:
      - echo "Starting build actions"
      - echo Build started on `date`
      - docker build -f $FOLDER1/$DFILE1 -t $REPO1:latest $FOLDER1
      - docker build -f $FOLDER2/$DFILE2 -t $REPO2:latest $FOLDER2
  post_build:
    commands:
      - echo Build completed on `date`
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPO1
      - docker push $REPO1:latest
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPO2
      - docker push $REPO2:latest

artifacts:
  files: 
    - $STATIC_FILES
  secondary-artifacts:
    s3_output_artifacts:
      files:
        - $STATIC_FILES
      name: "s3_output_artifacts"
      discard-paths: yes