version: 0.2

run-as: root

env:
  parameter-store: 
    docker_login: DOCKERHUB_LOGIN
    docker_password: DOCKERHUB_PASSWORD
  variables:
    APP1: 'sisoitherembo/apache-app:latest'
    APP2: 'sisoitherembo/nginx-app:latest'
    DFILE1: "apache.dockerfile"
    DFILE2: "nginx.dockerfile"
    FOLDER1: "apache-config"
    FOLDER2: "nginx-config"
    STATIC_FILES: "nginx-config/nginx-user/**/*"

phases:
  pre_build:
    commands:
      - echo "Starting docker-ce..."
      - docker login -p $docker_password -u $docker_login
      - echo "Docker-ce started!!!"
  build:
    commands:
      - echo "Starting build actions"
      - echo Build started on `date`
      - docker build -f $FOLDER1/$DFILE1 -t $APP1 $FOLDER1
      - docker build -f $FOLDER2/$DFILE2 -t $APP2 $FOLDER2
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $APP1
      - docker push $APP2

artifacts:
  files: 
    - $STATIC_FILES
  name: S3_output
  
      