#!/bin/bash
LOGIN=$(aws ssm get-parameters --name nginx-user --region us-east-1 --with-decryption --output text --query Parameters[].Value)
PASSWD=$(aws ssm get-parameters --name nginx-pass --region us-east-1 --with-decryption --output text --query Parameters[].Value)
HTPASSWD=$(echo $PASSWD | htpasswd -n -i $LOGIN)
ENCODED=$(echo $LOGIN:$PASSWD | base64)
sed -i "s(nginx.basic-auth:.*(nginx.basic-auth: \"$HTPASSWD\"(" ../manifests/nginx-app-deploy/config-map.yaml
sed -i "s(value: Basic.*(value: Basic $ENCODED(" ../manifests/nginx-app-deploy/deployment.yaml