version: "0.0.1"

networks:
  nginx-net:

services: 
  nginx-app:
    build: 
      context: nginx-config
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - /mnt/d/nginx-user:/home/nginx-user
    depends_on:
      - apache
    restart: always
    

  apache-app:
    build:
      context: apache-config
      dockerfile: apache.dockerfile
    ports:
      - "8080:80"
    restart: always

