- name: Start EC2 instances
  ec2: 
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key_id }}"
    region: "{{ aws_region }}"
    image: "{{ aws_image_ami }}"
    instance_type: "{{ aws_instance_type }}"
    key_name: "{{ aws_key_name }}"
    group: "{{ aws_security_group }}"
    instance_tags: { type: ansible, env: testing }
    exact_count: "{{ aws_instance_count }}"
    count_tag: { type: ansible }
    wait: yes
  register: ec2

- name: Add started EC2 instances to host groups
  add_host: 
    hostname: "{{ item.public_dns_name }}"
    groups: ec2_servers
  with_items: "{{ ec2.tagged_instances }}"

- name: Wait for SSH-agent started on the started hosts
  wait_for: 
    host: "{{ item.public_dns_name }}"
    port: 22
    search_regex: "OpenSSH" 
  with_items: "{{ ec2.tagged_instances }}"