apiVersion: v1
kind: Pod
metadata: 
  name : nginx-app
  namespace: nginx
  labels: 
    app : nginx-app
    env : prod
spec:
  containers:
  - name: nginx-app
    image: sisoitherembo/nginx-app:k8s
    ports:
      name: http
      protocol: TCP
      containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: "/etc/nginx/conf.d"
      readOnly: true
  
  - name: apache-app 
    image: sisoitherembo/apache-app:k8s   
    ports:
      name: http
      protocol: TCP
      containerPort: 8086
    volumeMounts:
    - name: apache-config
      mountPath: "/etc/apache2/"
      readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: nginx-config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: nginx-app-configmap
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "server.conf"
          path: "nginx.conf"
    - name: apache-config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: nginx-app-configmap
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "ports.conf"
          path: "apache.conf"
