groups:
- name: example
  rules:
  # Alert for any instance that is unreachable for >2 minutes.
    - alert: service_down
      expr: up == 0
      for: 2m
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

    - alert: prometheus_CPU-load
      expr: node_cpu_seconds_total{cpu="0", instance="Another-server", job="another-server_node-exporter", mode="iowait"} > 10
      for: 2m
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."

    - alert: another-server_RAM-load
      expr: node_memory_MemAvailable_bytes{job="another-server_node-exporter"} < 1024*1024*1024
      for: 2m
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."