groups:
- name: example
  rules:
  # Alert for any instance that is unreachable for >2 minutes.
    - alert: service_down
      expr: up == 0
      for: 2m
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

    - alert: CPU_high-load
      expr: 100 - (avg by(instance) (irate(node_cpu{mode="idle"}[5m])) * 100) > 70
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high CPU load."

    - alert: RAM_high-load
      expr: (sum(node_memory_MemTotal) - sum(node_memory_MemFree + node_memory_Buffers + node_memory_Cached) ) / sum(node_memory_MemTotal) * 100 > 85
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high RAM load."