groups:
- name: example
  rules:
  # Alert for any instance that is unreachable for >2 minutes.
    - alert: service_down
      expr: up == 0
      for: 2m
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

    - alert: CPU_high-load
      expr: (1- (avg(irate(node_cpu_seconds_total{job="CPU_node-exporter", mode="idle"}[5m]))))*100  > 50
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high CPU load."

    - alert: RAM_high-load
      expr: (sum(node_memory_MemTotal_bytes{job="RAM_node-exporter"}) - sum(node_memory_MemFree_bytes{job="RAM_node-exporter"} + node_memory_Buffers_bytes{job="RAM_node-exporter"} + node_memory_Cached_bytes{job="RAM_node-exporter"}) ) / sum(node_memory_MemTotal_bytes{job="RAM_node-exporter"}) * 100 > 50
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high RAM load."