global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'my-project'

rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs: 
        - targets: ['alert-manager:9093']


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

    - job_name: 'CPU_node-exporter'
    scrape_interval: 6s
    ec2_sd_configs:
      - region: us-east-2
        port: 9100
        filters:
          - name: tag:Metric
            values: 
              - CPU
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        replacement: '${1}:9100'
        target_label: __address__
      
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance

  - job_name: 'RAM_node-exporter'
    scrape_interval: 6s
    ec2_sd_configs:
      - region: us-east-2
        port: 9100
        filters:
          - name: tag:Metric
            values: 
              - RAM
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        replacement: '${1}:9100'
        target_label: __address__
      
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
