global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'my-project'

rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
    templateFiles:
      template_1.tmpl: |-
          {{ define "__title" }}{{ range .Alerts.Firing }}{{ .Labels.alertname }}{{ end }}{{ range .Alerts.Resolved }}{{ .Labels.alertname }}{{ end }}{{ end }}
          {{ define "alert_title" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if or (and (eq (len .Alerts.Firing) 1) (eq (len .Alerts.Resolved) 0)) (and (eq (len .Alerts.Firing) 0) (eq (len .Alerts.Resolved) 1)) }}{{ template "__title" . }}{{ end }}{{ end }}
          {{ define "alert_description"}}
          {{ if or (and (eq (len .Alerts.Firing) 1) (eq (len .Alerts.Resolved) 0)) (and (eq (len .Alerts.Firing) 0) (eq (len .Alerts.Resolved) 1)) }}
          {{ range .Alerts.Firing }}{{ .Annotations.description }} *{{ .Labels.severity | toUpper }}* :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*{{ end }}
          {{ range .Alerts.Resolved }}{{ .Annotations.description }} :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*{{ end }}
          {{ else }}
          {{ if gt (len .Alerts.Firing) 0 }}*Alerts Firing:*
          {{ range .Alerts.Firing }}- {{ .Annotations.description }} | *{{ .Labels.severity | toUpper }}* :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
          {{ end }}{{ end }}
          {{ if gt (len .Alerts.Resolved) 0 }}
          *Resolved:*
          {{ range .Alerts.Resolved }}- {{ .Annotations.description }} :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
          {{ end }}{{ end }}
          {{ end }}
          {{ end }}
    - scheme: http
      static_configs: 
        - targets: ['alert-manager:9093']


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometeheus_node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'another-server_node-exporter'
    scrape_interval: 6s
    ec2_sd_configs:
      - region: us-east-2
        port: 9100
        filters:
          - name: tag:Name
            values: 
              - Another-server
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        replacement: '${1}:9100'
        target_label: __address__
      
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
